<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <UseWPF>true</UseWPF>
    <AssemblyName>DeltaPlayer</AssemblyName>
    <RootNamespace>DeltaPlayer</RootNamespace>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>
  <ItemGroup><PackageReference Include="Melanchall.DryWetMidi" Version="7.2.0" /></ItemGroup>
  <ItemGroup><None Update="example.txt" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" /></ItemGroup>
</Project>
